## File di Configurazione

### _config.yml
```yaml
title: Vogs27
description: Projects and Ideas
url: "https://Vogs27.github.io"
baseurl: ""

# Tema
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

# Collezioni per i progetti
collections:
  progetti:
    output: true
    permalink: /:collection/:name/

# Plugin aggiuntivi
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Impostazioni Markdown
markdown: kramdown
highlighter: rouge

# Impostazioni autore
author:
  name: Alessandro Vogrig
  #email: tua-email@esempio.com
  github: Vogs27
  #linkedin: il-tuo-profilo-linkedin

# Menu di navigazione
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /progetti/
  - title: About
    url: /about/